name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{secrets.HOST}} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          touch .env
          echo "${{secrets.ENV}}" > .env
          rsync -avzp . '${{secrets.USER}}@${{secrets.HOST}}:~/stroycom'
          ssh ${{secrets.USER}}@${{secrets.HOST}} "cd ~/stroycom \
          && docker system prune -f \
          && npm ci \
          && npm run dev \
          && docker compose up -d \
          && docker exec project_app composer update \
          && docker exec project_app composer install \
          && docker exec project_app php artisan migrate \
          && docker exec project_app php artisan cache:clear \
          && docker exec project_app php artisan storage:link \
          && docker exec project_app php artisan route:cache"
