name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add ssh key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Deploy to server
        env:
          options: ssh -i ~/.ssh/key -o StrictHostKeyChecking=no
        run: |
          touch .env
          echo "${{secrets.ENV}}" > .env
          rsync --chown=www-data:www-data -e "$options" -avzpg . '${{secrets.USER}}@${{secrets.HOST}}:/var/www/stroycom'
          ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.HOST}} "cd /var/www/stroycom \
          && docker system prune -f \
          && npm ci \
          && npm run build \
          && docker compose up -d \
          && docker exec funnyholidays_app composer update --optimize-autoloader \
          && docker exec funnyholidays_app composer install --optimize-autoloader --no-dev \
          && docker exec funnyholidays_app php artisan migrate \
          && docker exec funnyholidays_app php artisan cache:clear \
          && docker exec funnyholidays_app php artisan storage:link"
